export const allComponents = {
  components: [
    'accordion',
    'alert',
    'avatar',
    'badge',
    'banner',
    'breadcrumb',
    'button',
    'button-group',
    'card',
    'carousel',
    'drawer',
    'dropdown',
    'footer',
    'jumbotron',
    'modal',
    'navbar',
    'rating',
    'sidebar',
    'spinner',
    'table',
    'tabs',
    'toast',
  ],
  formComponents: ['checkbox', 'input', 'radio', 'select', 'textarea', 'toggle'],
}
