/**
 * DO NOT EDIT, GENERATED FILE
 */

export const allDocs = {
  components: [
    'accordion',
    'alert',
    'avatar',
    'badge',
    'banner',
    'breadcrumb',
    'button',
    'button-group',
    'card',
    'carousel',
    'clipboard',
    'date-picker',
    'drawer',
    'dropdown',
    'footer',
    'jumbotron',
    'kbd',
    'list-group',
    'modal',
    'navbar',
    'pagination',
    'progress-bar',
    'rating',
    'sidebar',
    'spinner',
    'table',
    'tabs',
    'timeline',
    'toast',
    'tooltip',
  ],
  customize: ['dark-mode', 'theme'],
  forms: ['checkbox', 'input', 'radio', 'range', 'select', 'textarea', 'toggle'],
  'getting-started': ['introduction', 'quickstart', 'license'],
  typography: ['blockquote', 'heading', 'hr', 'link', 'list'],
}
